baseURL = ""
languageCode = "en-us"
title = "Hugo Whisper Theme"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "RTFM"
    url = "/rtfm/"
    weight = 3

[[menu.main]]
    name = "PBR"
    url = "/portland-stuff/"
    weight = 2


[params]
  google_analytics_id=""
  homepage_button_link = '/portland-stuff'
  homepage_button_text = 'portland stuff'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  ##homepage_image = 'https://media.giphy.com/media/4To7LSrMVVX6dL0dyZ/giphy.gif'
  homepage_image = 'https://media1.tenor.com/images/deb4de653575bc16494cd8e064351f02/tenor.gif?itemid=10836443'
  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://media1.tenor.com/images/deb4de653575bc16494cd8e064351f02/tenor.gif?itemid=10836443"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile  = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpikfly.com%2Fimages%2Fproducts%2F41%2F14858.jpg&f=1&nofb=1"
      standard  = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpikfly.com%2Fimages%2Fproducts%2F41%2F14858.jpg&f=1&nofb=1"
